# -*- coding: utf-8 -*-
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import emailSender
from smtplib import SMTP
import time
#----------------------------------------------------------------------------------------------------------------------#
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 667)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 591))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_chooseSenderMailAddress = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_chooseSenderMailAddress.setMinimumSize(QtCore.QSize(250, 0))
        self.comboBox_chooseSenderMailAddress.setSizeIncrement(QtCore.QSize(20, 20))
        self.comboBox_chooseSenderMailAddress.setBaseSize(QtCore.QSize(20, 20))
        self.comboBox_chooseSenderMailAddress.setIconSize(QtCore.QSize(24, 24))
        self.comboBox_chooseSenderMailAddress.setObjectName("comboBox_chooseSenderMailAddress")
        self.verticalLayout_2.addWidget(self.comboBox_chooseSenderMailAddress)
        self.comboBox_chooseReceiverMailAddress = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_chooseReceiverMailAddress.setObjectName("comboBox_chooseReceiverMailAddress")
        self.verticalLayout_2.addWidget(self.comboBox_chooseReceiverMailAddress)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_subject = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_subject.setText("")
        self.lineEdit_subject.setObjectName("lineEdit_subject")
        self.horizontalLayout_4.addWidget(self.lineEdit_subject)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit_message = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit_message.setObjectName("textEdit_message")
        self.horizontalLayout_2.addWidget(self.textEdit_message)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.pushButton_SendButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_SendButton.setFont(font)
        self.pushButton_SendButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_SendButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_SendButton.setAutoFillBackground(False)
        self.pushButton_SendButton.setObjectName("pushButton_SendButton")
        self.horizontalLayout_3.addWidget(self.pushButton_SendButton)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        self.pushButton_AddSenderMail = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_AddSenderMail.setFont(font)
        self.pushButton_AddSenderMail.setObjectName("pushButton_AddSenderMail")
        self.horizontalLayout_3.addWidget(self.pushButton_AddSenderMail)
        self.pushButton_AddReceiverMail = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_AddReceiverMail.setFont(font)
        self.pushButton_AddReceiverMail.setObjectName("pushButton_AddReceiverMail")
        self.horizontalLayout_3.addWidget(self.pushButton_AddReceiverMail)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        emailSender.readFromFile()
        for i in emailSender.senderMailAddresses:
            self.comboBox_chooseSenderMailAddress.addItem(i)
        for i in emailSender.receiverMailAddresses:
            self.comboBox_chooseReceiverMailAddress.addItem(i)

        self.comboBox_chooseSenderMailAddress.activated[str].connect(self.onSelectedComboBoxSenderMail)
        self.comboBox_chooseReceiverMailAddress.activated[str].connect(self.onSelectedComboBoxReceiverMail)
        self.pushButton_SendButton.clicked.connect(self.send)
        self.pushButton_AddSenderMail.clicked.connect(self.addEmail)
        self.pushButton_AddReceiverMail.clicked.connect(self.refresh)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "e-m@il Sender 1.0.0         by SimpleAppsInc"))
        self.label_2.setText(_translate("MainWindow", "Sender mail address"))
        self.label.setText(_translate("MainWindow", "Receiver mail address"))
        self.label_3.setText(_translate("MainWindow", "SUBJECT:"))
        self.pushButton_SendButton.setText(_translate("MainWindow", "SEND ->"))
        self.pushButton_AddSenderMail.setText(_translate("MainWindow", "ADD SENDER/RECEIVER MAİL ADDRESS"))
        self.pushButton_AddReceiverMail.setText(_translate("MainWindow", "REFRESH"))

    def onSelectedComboBoxSenderMail(self,mail):
        self.pushButton_SendButton.setText("SEND ->")
        for i in range(0,len(emailSender.senderMailAddresses)):
            if emailSender.senderMailAddresses[i] == mail:
                emailSender.senderIndex = i


    def onSelectedComboBoxReceiverMail(self,mail):
        self.pushButton_SendButton.setText("SEND ->")
        for i in range(0, len(emailSender.receiverMailAddresses)):
            if emailSender.receiverMailAddresses[i] == mail:
                emailSender.receiverIndex = i



    def send(self):
        ssmtp = None
        try:
            for i in range(len(emailSender.smtpp)):
                a = emailSender.smtpp[i].split(";")
                for j in a:
                    if j in emailSender.senderMailAddresses[emailSender.senderIndex]:
                        ssmtp = emailSender.smtps[i]


            message = "From:  {0}\nSubject: {1}\n\n{2}".format(emailSender.senderMailAddresses[emailSender.senderIndex],
                                                               self.lineEdit_subject.text(),
                                                               self.textEdit_message.toPlainText())
            mail = SMTP(ssmtp, 587)
            mail.ehlo()
            mail.starttls()
            mail.login(emailSender.senderMailAddresses[emailSender.senderIndex],
                       emailSender.senderPasswords[emailSender.senderIndex])
            mail.sendmail(emailSender.senderMailAddresses[emailSender.senderIndex],
                          emailSender.receiverMailAddresses[emailSender.receiverIndex], message.encode("utf8"))
            self.pushButton_SendButton.setText("Sended")


        except Exception as a:
            self.lineEdit_subject.setText(str(a))
            self.pushButton_SendButton.setText("An Error Occured")

    def addEmail(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = emailSender.Ui_MainWindow_addmailadress()
        self.ui.setupUi(self.window)
        self.window.show()

    def refresh(self):
        emailSender.readFromFile()
        self.comboBox_chooseSenderMailAddress.clear()
        self.comboBox_chooseReceiverMailAddress.clear()
        for i in emailSender.senderMailAddresses:
            self.comboBox_chooseSenderMailAddress.addItem(i)
        for i in emailSender.receiverMailAddresses:
            self.comboBox_chooseReceiverMailAddress.addItem(i)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())